format = """
$directory\
$git_branch\
$git_status\
$git_metrics\
$fill
$character
"""

[directory]
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
truncation_length = 20

[git_metrics]
disabled=false

[git_state]
disabled=false

[git_status]
disabled = false

[fill]
symbol = ' '
