format = """
$directory\
$git_branch\
$git_status\
$fill\
$time\
$line_break\
$character
"""

[fill]
symbol=" " 

[time]
format = '[$time]($style) '
disabled=false
time_format = "%I:%M%p"

[kubernetes]
format = 'on [⛵ ($user on )($cluster in )$context \($namespace\)](dimmed green) '
disabled = false
