[general]
live_config_reload = true

[window]
decorations = "none"
dynamic_padding = true
option_as_alt = "Both"
startup_mode = "Maximized"

[window.padding]
x = 0
y = 0

[cursor.style]
shape = "Beam"
blinking = "On"

[mouse]
hide_when_typing = true

[scrolling]
history = 10_000

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[font]
size = 14

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Light"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.offset]
y = 1

[terminal.shell]
program = "/Users/robbienohra/.cargo/bin/nu"
args = [ "-e", "zellij attach -c" ]
# args = ["--no-config-file", "--no-history"]

 # https://github.com/alacritty/alacritty/issues/7622
[keyboard]
bindings = [
  { key = "k", mods = "Control", chars = "\u0003" }, # sigint
]

# color theme

# Kanagawa Alacritty Colors
[colors.primary]
background = "0x1f1f28"
foreground = "0xdcd7ba"

[colors.normal]
black = "0x090618"
red = "0xc34043"
green = "0x76946a"
yellow = "0xc0a36e"
blue = "0x7e9cd8"
magenta = "0x957fb8"
cyan = "0x6a9589"
white = "0xc8c093"

[colors.bright]
black = "0x727169"
red = "0xe82424"
green = "0x98bb6c"
yellow = "0xe6c384"
blue = "0x7fb4ca"
magenta = "0x938aa9"
cyan = "0x7aa89f"
white = "0xdcd7ba"

[colors.selection]
background = "0x2d4f67"
foreground = "0xc8c093"

[[colors.indexed_colors]]
index = 16
color = "0xffa066"

[[colors.indexed_colors]]
index = 17
color = "0xff5d62"
