[general]
live_config_reload = true

[window]
decorations = "none"
dynamic_padding = true
option_as_alt = "Both"
startup_mode = "Maximized"

[window.padding]
x = 0
y = 0

[cursor.style]
shape = "Beam"
blinking = "On"

[mouse]
hide_when_typing = true

[scrolling]
history = 10_000

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[font]
size = 14

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Light"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.offset]
y = 1

[terminal.shell]
program = "/Users/robbienohra/.cargo/bin/nu"
args = [ "-e", "zellij attach -c" ]
# args = ["--no-config-file", "--no-history"]

 # https://github.com/alacritty/alacritty/issues/7622
[keyboard]
bindings = [
  { key = "k", mods = "Control", chars = "\u0003" }, # sigint
]

# TokyoNight Alacritty Colors
# Default colors
[colors.primary]
background = '#1a1b26'
foreground = '#c0caf5'

#[colors.cursor]
#cursor = '#c0caf5'
#text = '#1a1b26'

# Normal colors
[colors.normal]
black = '#15161e'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

# Bright colors
[colors.bright]
black = '#414868'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#c0caf5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff9e64'

[[colors.indexed_colors]]
index = 17
color = '#db4b4b'

