version: 2
root-markers:
  - .git/
lint-debounce: 1s
tools:
  go-gofmt: &go-gofmt
    # executed against stdin by default
    format-command: 'gofmt'
    format-stdin: true
  lua-stylua: &lua-stylua
    format-command: 'stylua --config-path ~/.config/stylua.toml -'
    format-stdin: true
  yaml-yamlfmt: &yaml-yamlfmt
    format-command: 'yamlfmt -'
    format-stdin: true
  markdown-pandoc: &markdown-pandoc
    format-command: 'pandoc --wrap=none -f gfm -t gfm -s --tab-stop=2'
    format-stdin: true
  prettierd: &prettierd
    format-command: >
      prettierd ${INPUT} ${--range-start=charStart} ${--range-end=charEnd} ${--tab-width=tabSize}

    format-stdin: true
    root-markers:
      - .prettierrc
      - .prettierrc.json
      - .prettierrc.js
      - .prettierrc.yml
      - .prettierrc.yaml
      - .prettierrc.json5
      - .prettierrc.mjs
      - .prettierrc.cjs
      - .prettierrc.toml
  pg-format: &pg-format
    format-command: 'pg_format'
  html-prettier: &html-prettier
    format-command: 'prettierd ${INPUT} ${--tab-width:tabWidth} ${--single-quote:singleQuote} --parser html'
  cpp-clang-format: &cpp-clang-format
    format-command: 'clang-format -'
    format-stdin: true
  python-yapf: &python-yapf
    format-command: 'yapf --quiet'
    format-stdin: true
  terraform: &terraform
    format-command: 'terraform fmt -'
    format-stdin: true
  shell-shfmt: &shell-shfmt
    format-command: 'shfmt -'
    format-stdin: true
  tex-latexindent: &tex-latexindent
    format-command: 'latexindent -'
    format-stdin: true
  hjson: &hjson
    format-command: 'hjson -'
    format-stdin: true
languages:
  go:
    - <<: *go-gofmt
  lua:
    - <<: *lua-stylua
  yaml:
    - <<: *yaml-yamlfmt
  markdown:
    - <<: *markdown-pandoc
  javascript:
    - <<: *prettierd
  json:
    - <<: *prettierd
  hjson:
    - <<: *hjson
  typescript:
    - <<: *prettierd
  sql:
    - <<: *pg-format
  html:
    - <<: *html-prettier
  cpp:
    - <<: *cpp-clang-format
  tex:
    - <<: *tex-latexindent
  python:
    - <<: *python-yapf
  tf:
    - <<: *terraform
  sh:
    - <<: *shell-shfmt
