require("nvim-treesitter.configs").setup {
  rainbow = {
    enable = true,
  },
  ensure_installed = {
    "bash",
    "cmake",
    "cpp",
    "css",
    "dockerfile",
    "go",
    "hcl",
    "html",
    "javascript",
    "json",
    "lua",
    "markdown",
    "markdown_inline",
    "prisma",
    "python",
    "rust",
    "scss",
    "svelte",
    "terraform",
    "toml",
    "typescript",
    "vim",
    "vue",
    "yaml",
  },
  autotag = {
    enable = true,
    filetypes = {
      "html",
      "javascript",
      "typescript",
      "javascriptreact",
      "typescriptreact",
      "svelte",
      "vue",
      "tsx",
      "jsx",
      "rescript",
    },
  },
  highlight = {
    enable = true,
  },
}
