return {
  "tpope/vim-fugitive",
  "tpope/vim-repeat",
  "tpope/vim-rhubarb", -- required by fugitive to :Gbrowse
  "tpope/vim-scriptease",
  "tpope/vim-surround",
  "tpope/vim-unimpaired",
  "tpope/vim-vinegar",
  {
    "nvim-lualine/lualine.nvim",
    dependencies = { "kyazdani42/nvim-web-devicons", opt = true },
  },
  { "luisiacc/gruvbox-baby", branch = "main" },
  "lewis6991/impatient.nvim",
  { "junegunn/fzf", build = ":call fzf#install()" },
  { "junegunn/fzf.vim" },
  {

    "hrsh7th/nvim-cmp",
    dependencies = {
      "hrsh7th/cmp-buffer",
      "hrsh7th/cmp-cmdline",
      "hrsh7th/cmp-nvim-lsp",
      "hrsh7th/cmp-path",
      "hrsh7th/cmp-vsnip",
      "hrsh7th/vim-vsnip",
      "hrsh7th/vim-vsnip-integ",
    },
    lazy = true,
    event = "InsertEnter",
  },
  "Yggdroot/indentLine",
  "jose-elias-alvarez/null-ls.nvim",
  "nvim-lua/plenary.nvim",
  "mfussenegger/nvim-dap",
  "mhinz/vim-signify",
  "neovim/nvim-lspconfig",
  "norcalli/nvim-colorizer.lua",
  "numToStr/Comment.nvim",
  "p00f/nvim-ts-rainbow",
  "williamboman/mason.nvim",
  "williamboman/mason-lspconfig.nvim",
  "windwp/nvim-autopairs",
  "windwp/nvim-ts-autotag",
  "junegunn/vim-peekaboo",
  { "nvim-treesitter/nvim-treesitter", build = ":TSUpdate" },
  "WhoIsSethDaniel/mason-tool-installer.nvim",
  "ThePrimeagen/harpoon",
}
