alias git="/opt/homebrew/bin/git"
alias sz='source ~/.zshrc'
alias g='git'
alias b="bash"
alias v="nvim"
alias n="nvim ."
alias l="exa -l --icons"
alias la="exa -la"
alias lt="exa --tree"
alias k="kubectl"
alias tf="terraform"
